---
- name: Check if Docker binary is installed
  stat:
    path: /usr/bin/docker
  register: docker

- name: Install docker
  include_tasks: docker.yml
  when: not docker.stat.exists

- name: Set up systemd for Docker
  include_tasks: systemd.yml
  when: ansible_service_mgr == "systemd"
