---
- gather_facts: false
  hosts: ubuntu2004
  name: Prepare Ubuntu 20.04
  tasks:
    - name: Raw update apt repos
      raw: apt-get update -y
      changed_when: false
    - name: Raw install packages
      raw: apt-get install python3 sudo -y
      changed_when: false
    - name: Create ubuntu group
      group:
        name: ubuntu
    - name: Create ubuntu user
      user:
        name: ubuntu
        group: ubuntu
